# Generated by Django 5.2.10 on 2026-02-01 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Building Purpose')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Building Purpose',
                'verbose_name_plural': 'Building Purposes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Project Name')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('postcode', models.CharField(blank=True, max_length=10, verbose_name='Postcode')),
                ('built_in', models.PositiveIntegerField(blank=True, help_text='Year when the project was completed', null=True, verbose_name='Built In')),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, help_text='Approximate contract value in GBP', max_digits=12, null=True, verbose_name='Contract Value (£)')),
                ('contract_value_confidential', models.BooleanField(default=False, verbose_name='Contract Value is Confidential')),
                ('description', models.TextField(blank=True, verbose_name='Project Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/%Y/%m/%d/', verbose_name='Main Project Image')),
                ('construction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.constructiontype', verbose_name='Construction Type')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.buildingpurpose', verbose_name='Building Purpose')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-built_in', 'name'],
            },
        ),
    ]
