# Generated by Django 5.2.10 on 2026-02-01 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_buildingpurpose_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='purpose',
        ),
        migrations.DeleteModel(
            name='BuildingPurpose',
        ),
    ]
