# Generated by Django 5.2.10 on 2026-02-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_purpose_delete_buildingpurpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug (for URL)'),
        ),
    ]
