# Generated by Django 5.2.10 on 2026-02-01 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designers', '0001_initial'),
        ('projects', '0003_remove_project_purpose_delete_buildingpurpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lead_architect', 'Lead Architect'), ('structural_engineer', 'Structural Engineer'), ('senior_structural_engineer', 'Senior Structural Engineer'), ('architectural_designer', 'Architectural Designer'), ('technical_lead', 'Technical Lead'), ('structural_consultant', 'Structural Consultant'), ('other', 'Other')], max_length=50, verbose_name='Role in the project')),
                ('contribution', models.TextField(blank=True, verbose_name='Contribution / Notes')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='designers.designer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='projects.project')),
            ],
            options={
                'verbose_name': 'Team Participation',
                'verbose_name_plural': 'Team Participations',
                'ordering': ['project', 'role'],
                'unique_together': {('project', 'designer')},
            },
        ),
    ]
