# Generated by Django 5.2.10 on 2026-04-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='role',
            field=models.CharField(choices=[('architect', 'Architect'), ('lead_architect', 'Lead Architect'), ('architectural_designer', 'Architectural Designer'), ('structural_engineer', 'Structural Engineer'), ('senior_structural_engineer', 'Senior Structural Engineer'), ('structural_designer', 'Structural Designer'), ('technical_lead', 'Technical Lead'), ('structural_consultant', 'Structural Consultant'), ('other', 'Other')], max_length=50, verbose_name='Role in the project'),
        ),
    ]
