# Generated by Django 5.2.10 on 2026-02-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full name')),
                ('profession', models.CharField(help_text='e.g. Architect, Engineer, Technician, Surveyor', max_length=100, verbose_name='Profession / Specialty')),
                ('initials', models.CharField(blank=True, max_length=4, verbose_name='Initials (for drawings/signatures)')),
                ('short_bio', models.TextField(blank=True, verbose_name='Short bio / Experience')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
